### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by Joseerdriiguez** [noia-network/noia-node-gui#11] opened 2018-06-13 04:59 UTC
When i open the .exe file (noia-node-gui-0.1.1-x86_64_win) on my win7 laptop, it makes my computer kind of slow for a few of seconds, then this appears:

![ss](https://user-images.githubusercontent.com/40225258/41330987-8cb14214-6ea4-11e8-8a16-5533885b372b.png)

 And after that, it just throw this message:

![sin titulo](https://user-images.githubusercontent.com/40225258/41330887-00b6522c-6ea4-11e8-8953-005c4e815c5b.png)
 
Don't know what's going on with the file, please help us and thanks!!!

Here´s the log:
[SquirrelSetup.log](https://github.com/noia-network/noia-node-gui/files/2096674/SquirrelSetup.log)

**Comment by Dancia** [comment] 2018-06-13 09:01
Please try the latest Node GUI version available in [releases](https://github.com/noia-network/noia-node-gui/releases).

At the time of writing it is version 0.2.5.

**Comment by Dancia** [comment] 2018-06-13 12:40
Duplicate of #9.

**Closed** 2018-06-13 12:41 UTC
